### ISSUE TITLE
[windows][雷电模拟器]无法连接游戏

### ISSUE THREAD

**Issue by cym1ym** [cndaqiang/WZRY#59]
- [ ] 我已阅读全新的[项目主页](https://cndaqiang.github.io/wzry.doc/)
- [ ] 我已阅读全新的[安装指南](https://cndaqiang.github.io/wzry.doc/guide/install/)
- [ ] 我已查看[常见问题收录](https://cndaqiang.github.io/wzry.doc/QA/), 并未找到重复问题
- [ ] 我已可以顺利控制一台模拟器进行对战

**只处理release大于2.2.0的issues, 老版本遇到的issues不予处理**

为了快速解决问题，请尽可能的提供这些内容，并礼貌**友善**的提问
* 执行结果
* 0>Android:///127.0.0.1:5555:开始第1/3次连接
[11-13 17:28:03]0>Android:///127.0.0.1:5555:链接失败
[11-13 17:28:07]0>Android:///127.0.0.1:5555:链接失败,启动设备再次连接
[11-13 17:28:07]0>run_command.启动设备.连接设备.__init__.__init__.single_execute.execute.<module>
[11-13 17:28:07]0>  sysrun:'D:\anaconda\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe' disconnect 127.0.0.1:5555
[11-13 17:28:29]0>尝试启动设备中...
Traceback (most recent call last):
  File "D:\anaconda\Lib\site-packages\airtest_mobileauto\control.py", line 1963, in single_execute
    task_instance = self.task_class(*self.args, **self.kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sgs\WZRY-2.1.2\wzry.py", line 272, in __init__
    self.移动端 = deviceOB(mynode=self.mynode, totalnode=self.totalnode, LINK=self.LINK)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\site-packages\airtest_mobileauto\control.py", line 1450, in __init__
    self.连接设备()
  File "D:\anaconda\Lib\site-packages\airtest_mobileauto\control.py", line 1497, in 连接设备
    self.启动设备()
  File "D:\anaconda\Lib\site-packages\airtest_mobileauto\control.py", line 1567, in 启动设备
    BossKey = Settings.BossKey[self.mynode]
              ^^^^^^^^^^^^^^^^
AttributeError: type object 'Settings' has no attribute 'BossKey'
[11-13 17:28:29]0>Error in single_execute with mynode=0
[11-13 17:28:29]0>single_execute finished with mynode=0
* 配置文件
* 运行目录
* 游戏页面
* 模拟器设置页面
* cmd/powershell/terminal/vscode/pycharm等运行界面截图

**Comment by cndaqiang** [comment]
你使用的是老版本
> ”File "D:\sgs\WZRY-2.1.2\wzry.py", line 272, in init“

只处理release大于2.2.0的issues, 老版本遇到的issues不予处理

**Comment by cndaqiang** [comment]
最新版本的`airtest_mobileauto`已修复此问题
```
python -m pip install airtest_mobileauto --upgrade
```

原因：
* 未配置模拟器的参数, 脚本无法启动模拟器
* 运行脚本前没有启动模拟器，脚本无法连接
* 脚本在尝试*硬*启动`127.0.0.1:5555`出错
